# dataset测试

In [1]:
from dataset import ModelNetDataLoader
from torch.utils.data import DataLoader

DATA_PATH = 'data/modelnet40_normal_resampled/'
TRAIN_DATASET = ModelNetDataLoader(
    root=DATA_PATH, npoint=1024, 
    split='test' , normal_channel=True, classes=10)

#os.environ["CUDA_VISIBLE_DEVICES"] = '0'
print(len(TRAIN_DATASET))
print(len(TRAIN_DATASET[500][0]))
print(len(TRAIN_DATASET[500][1]))
TRAIN_DATASET[500][1]

The size of test data is 908
908
1024
1


array([5], dtype=int32)

In [1]:
from visualizer.show3d_balls import showpoints,cmap
# from ShapeNetDataLoader import PartNormalDataset
root = '../data/shapenetcore_partanno_segmentation_benchmark_v0_normal/'
dataset = ModelNetDataLoader(root = root, npoints=2048, split='test', normal_channel=False)
idx = np.random.randint(0, len(dataset))
data = dataset[idx]
point_set, _, seg = data
choice = np.random.choice(point_set.shape[0], 2048, replace=True)
point_set, seg = point_set[choice, :], seg[choice]
seg = seg - seg.min()
gt = cmap[seg, :]
pred = cmap[seg, :]
showpoints(point_set, gt, c_pred=pred, waittime=0, showrot=False, magnifyBlue=0, freezerot=False,
            background=(255, 255, 255), normalizecolor=True, ballradius=10)

In [20]:
TRAIN_DATASET[1000][1]

array([2, 2, 2, ..., 2, 2, 2], dtype=int32)

In [2]:
trainDataLoader = DataLoader(
        TRAIN_DATASET , batch_size=4, 
        shuffle=True  , num_workers=8)
 #遍历
len(trainDataLoader)

227

In [4]:
train_features, train_labels = next(iter(trainDataLoader))
print(train_features.shape) 
print(train_labels.shape) 
train_labels

torch.Size([4, 1024, 6])
torch.Size([4, 1])


tensor([[4],
        [1],
        [4],
        [1]], dtype=torch.int32)

In [17]:
from train_cls import *
# cfg.num_point = 1024
# model = getattr(importlib.import_module('models.{}.model'.format('Hengshuang')), 'PointTransformerCls')(cfg).cuda()

In [24]:
target = train_labels[:,0]
target

tensor([2, 4, 2, 8], dtype=torch.int32)

In [23]:
np.unique(target)

array([2, 4, 8], dtype=int32)

In [25]:
target==2

tensor([ True, False,  True, False])

In [26]:
cat_idex = (target==2)
cat_idex

tensor([ True, False,  True, False])

In [27]:
target[cat_idex].long().data

tensor([2, 2])

In [30]:
cat_idex.sum().item()

2

In [35]:
pred = torch.Tensor([1,2])


In [36]:
pred.eq(target[cat_idex].long().data)

tensor([False,  True])

In [41]:
train_features[target==2].size()

torch.Size([2, 1024, 6])

In [40]:
train_features[target==2].size()[0]

2

In [ ]:
import random
import math
import matplotlib.pyplot as plt

M = 50 # 所有的点数量
N = 10 # fps采样点数量
x = []
y = []
xy = []

# 生成数据
random.seed(0)
for _ in range(M):
    px = round(random.uniform(1, 10), 2)  # 生成随机数，浮点类型 控制2位精度
    py = round(random.uniform(1, 10), 2)
    x.append(px)
    y.append(py)
    xy.append((px, py))

xy

In [ ]:
plt.figure(figsize=(10, 4))
plt.subplot(121)
plt.title('init_points')
plt.scatter(x, y, marker='o', c='r', edgecolors='b', s=200)

In [ ]:
select = []
rest = [num for num in range(0, M)]
max_dist = -99999
farthest_point = 99999

In [ ]:
# step 1 随机选择一个点
random.seed(1)
ind = random.randint(0, M - 1)

select.append(ind)
rest.remove(ind)
# print('select', select)
# print('rest', rest)

In [17]:
import numpy as np
import torch
a=torch.Tensor([1,2,3,4,5,6,6])
b=torch.Tensor([1,2,2,2,5,6,8])
print(np.unique(a))
print((a==6).sum()/2)
b[a==6]

[1. 2. 3. 4. 5. 6.]
tensor(1.)


tensor([6., 8.])