# dataset测试

In [4]:
from dataset import ModelNetDataLoader
from torch.utils.data import DataLoader

DATA_PATH = 'data/modelnet40_normal_resampled/'
TRAIN_DATASET = ModelNetDataLoader(
    root=DATA_PATH, npoint=1024, 
    split='train' , normal_channel=True)

os.environ["CUDA_VISIBLE_DEVICES"] = '0'
print(len(TRAIN_DATASET))
print(len(TRAIN_DATASET[9000][0]))
TRAIN_DATASET[9000][1]

The size of train data is 9843
9843
1024


array([36], dtype=int32)

In [ ]:
trainDataLoader = DataLoader(
        TRAIN_DATASET , batch_size=4, 
        shuffle=True  , num_workers=8)
train_features, train_labels = next(iter(trainDataLoader)) #遍历

In [ ]:
import random
import math
import matplotlib.pyplot as plt

M = 50 # 所有的点数量
N = 10 # fps采样点数量
x = []
y = []
xy = []

# 生成数据
random.seed(0)
for _ in range(M):
    px = round(random.uniform(1, 10), 2)  # 生成随机数，浮点类型 控制2位精度
    py = round(random.uniform(1, 10), 2)
    x.append(px)
    y.append(py)
    xy.append((px, py))

xy

In [ ]:
plt.figure(figsize=(10, 4))
plt.subplot(121)
plt.title('init_points')
plt.scatter(x, y, marker='o', c='r', edgecolors='b', s=200)

In [ ]:
select = []
rest = [num for num in range(0, M)]
max_dist = -99999
farthest_point = 99999

In [ ]:
# step 1 随机选择一个点
random.seed(1)
ind = random.randint(0, M - 1)

select.append(ind)
rest.remove(ind)
# print('select', select)
# print('rest', rest)

In [17]:
import numpy as np
import torch
a=torch.Tensor([1,2,3,4,5,6,6])
b=torch.Tensor([1,2,2,2,5,6,8])
print(np.unique(a))
print((a==6).sum()/2)
b[a==6]

[1. 2. 3. 4. 5. 6.]
tensor(1.)


tensor([6., 8.])